# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1399181881);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1398576146);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1398576266);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.lastDir", "/home/valliant/Desktop");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.slowStartup.averageTime", 4728);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140319103444");
user_pref("browser.startup.homepage_override.mstone", "24.4.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1398662545689");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1398576145689");
user_pref("datareporting.sessions.current.activeTicks", 24);
user_pref("datareporting.sessions.current.firstPaint", 4521);
user_pref("datareporting.sessions.current.main", 902);
user_pref("datareporting.sessions.current.sessionRestored", 4636);
user_pref("datareporting.sessions.current.startTime", "1399181758901");
user_pref("datareporting.sessions.current.totalTime", 171);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.1", "{\"s\":1398600443647,\"a\":13,\"t\":118,\"c\":false,\"m\":889,\"fp\":3990,\"sr\":4766}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1398602828497,\"a\":17,\"t\":120,\"c\":false,\"m\":899,\"fp\":2868,\"sr\":3005}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1398613258079,\"a\":24,\"t\":119,\"c\":false,\"m\":948,\"fp\":3473,\"sr\":3533}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1398615863600,\"a\":13,\"t\":116,\"c\":false,\"m\":11,\"fp\":844,\"sr\":894}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1398646482558,\"a\":18,\"t\":119,\"c\":false,\"m\":844,\"fp\":4006,\"sr\":4126}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1398648802370,\"a\":6,\"t\":30,\"c\":false,\"m\":1186,\"fp\":5049,\"sr\":5169}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.4.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1398568249000,\"rdfTime\":1395229329000}}}]");
user_pref("extensions.lastAppVersion", "24.4.0");
user_pref("extensions.lastPlatformVersion", "24.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140319103444");
user_pref("gecko.mstone", "24.4.0");
user_pref("idle.lastDailyNotification", 1399181985);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.backup.ftp", "");
user_pref("network.proxy.backup.ftp_port", 0);
user_pref("network.proxy.backup.socks", "");
user_pref("network.proxy.backup.socks_port", 0);
user_pref("network.proxy.backup.ssl", "");
user_pref("network.proxy.backup.ssl_port", 0);
user_pref("network.proxy.ftp", "proxy.its.ac.id");
user_pref("network.proxy.ftp_port", 8080);
user_pref("network.proxy.http", "proxy.its.ac.id");
user_pref("network.proxy.http_port", 8080);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("network.proxy.socks", "proxy.its.ac.id");
user_pref("network.proxy.socks_port", 8080);
user_pref("network.proxy.ssl", "proxy.its.ac.id");
user_pref("network.proxy.ssl_port", 8080);
user_pref("network.proxy.type", 0);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 45083);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1399181759);
user_pref("toolkit.telemetry.previousBuildID", "20140319114152");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1401168149);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
